package com.fcfb.arceus.dto.request

data class PostseasonFieldRequest(
    val turfColor: String? = null,
    val endZoneFont: String? = null,
    val centerLogoUrl: String? = null,
    val wallColor: String? = null,
    val wallDesign: String? = null,
    val wallText: String? = null,
    val wallTextOutlineColor: String? = null,
    val wallTextFont: String? = null,
    val goalPostColor: String? = null,
    val goalPostStyle: String? = null,
    val yardNumberOutlineColor: String? = null,
    val redZoneBorderColor: String? = null,
    val midfieldBorderColor: String? = null,
    val sidelineAccentColor: String? = null,
    val leftSidelineColor: String? = null,
    val rightSidelineColor: String? = null,
    val leftRedZoneColor: String? = null,
    val rightRedZoneColor: String? = null,
    val leftEndZoneText: String? = null,
    val rightEndZoneText: String? = null,
    val leftEndZoneLogoUrl: String? = null,
    val rightEndZoneLogoUrl: String? = null,
    val leftEndZoneLogoSource: String? = null,
    val rightEndZoneLogoSource: String? = null,
    val leftEndZoneFont: String? = null,
    val rightEndZoneFont: String? = null,
    val rightWallDesign: String? = null,
    val rightWallText: String? = null,
    val yardNumberFont: String? = null,
    val yardNumberArrowAlign: String? = null,
    val yardNumberOutlineWidth: Double? = null,
    val endZoneOutlineWidth: Double? = null,
    val wallTextOutlineWidth: Double? = null,
    val yardNumberSource: String? = null,
    val yardNumberTeamSlot: String? = null,
)
