package com.fcfb.arceus.dto.request

/** Editable home field settings. A null [fieldNumberOutlineColor] means the yard numbers are drawn without an outline. */
data class TeamFieldRequest(
    val turfColor: String? = null,
    val endZoneColor: String? = null,
    val endZoneTextColor: String? = null,
    val endZoneOutlineColor: String? = null,
    val endZoneTextLeft: String? = null,
    val endZoneTextRight: String? = null,
    val endZoneLogoEnabled: Boolean? = null,
    val endZoneLogoSource: String? = null,
    val endZoneLogoUrl: String? = null,
    val endZoneLogoSize: Double? = null,
    val endZoneOutlineEnabled: Boolean? = null,
    val wallLogoSource: String? = null,
    val wallLogoUrl: String? = null,
    val recolorConferenceLogo: Boolean? = null,
    val midfieldLogoSize: Double? = null,
    val leftEndZoneFont: String? = null,
    val rightEndZoneFont: String? = null,
    val rightWallDesign: String? = null,
    val rightWallText: String? = null,
    val yardNumberFont: String? = null,
    val conferenceLogoColorMap: String? = null,
    val endZoneFont: String? = null,
    val midfieldLogoUrl: String? = null,
    val midfieldLogoSource: String? = null,
    val fieldNumberOutlineColor: String? = null,
    val redZoneBorderColor: String? = null,
    val oobLineColor: String? = null,
    val wallColor: String? = null,
    val wallDesign: String? = null,
    val wallText: String? = null,
    val wallTextOutlineColor: String? = null,
    val goalPostColor: String? = null,
    val goalPostStyle: String? = null,
    val quarterLogoUrl: String? = null,
    val quarterLogoSource: String? = null,
)
