package com.fcfb.arceus.dto.request

/**
 * Editable uniform settings. Primary and secondary colors are deliberately absent: those belong to the team record and
 * are copied into the uniform, so exposing them here would give them two sources of truth.
 */
data class TeamUniformRequest(
    val tertiaryColor: String? = null,
    val helmetColor: String? = null,
    val secondaryHelmetColor: String? = null,
    val facemaskColor: String? = null,
    val helmetLogoMode: String? = null,
    val helmetLogoSource: String? = null,
    val helmetNumberColor: String? = null,
    val helmetNumberFont: String? = null,
    val jerseyNumberFont: String? = null,
    val logoUrl: String? = null,
    val hasLogo: Boolean? = null,
    val hasStripe: Boolean? = null,
    val stripeColor: String? = null,
    val stripeType: String? = null,
    val secondaryStripeColor: String? = null,
    val jerseyColor: String? = null,
    val numberColor: String? = null,
    val numberOutlineColor: String? = null,
    val awayNumberColor: String? = null,
    val awayNumberOutlineColor: String? = null,
    val altFacemaskColor: String? = null,
    val altHelmetNumberColor: String? = null,
    val altHelmetLogoMode: String? = null,
    val altHelmetLogoSource: String? = null,
    val altHasLogo: Boolean? = null,
    val altLogoUrl: String? = null,
    val altLogoSize: Double? = null,
    val altLogoX: Double? = null,
    val altLogoY: Double? = null,
    val altLogoRotation: Double? = null,
    val altHasStripe: Boolean? = null,
    val altStripeColor: String? = null,
    val altStripeType: String? = null,
    val altSecondaryStripeColor: String? = null,
    val pantsColor: String? = null,
    val awayPantsColor: String? = null,
    val logoSize: Double? = null,
    val logoX: Double? = null,
    val logoY: Double? = null,
    val logoRotation: Double? = null,
)
