package com.fcfb.arceus.enums.records

/**
 * Enum representing all possible stat types that can be tracked as records
 * Based on all fields from the GameStats model
 */
enum class Stats {
    // Basic Game Info
    SCORE,

    // Passing Stats
    PASS_ATTEMPTS,
    PASS_COMPLETIONS,
    PASS_COMPLETION_PERCENTAGE,
    PASS_YARDS,
    LONGEST_PASS,
    PASS_TOUCHDOWNS,
    PASS_SUCCESSES,
    PASS_SUCCESS_PERCENTAGE,

    // Rushing Stats
    RUSH_ATTEMPTS,
    RUSH_SUCCESSES,
    RUSH_SUCCESS_PERCENTAGE,
    RUSH_YARDS,
    LONGEST_RUN,
    RUSH_TOUCHDOWNS,

    // Total Offense
    TOTAL_YARDS,
    AVERAGE_YARDS_PER_PLAY,
    FIRST_DOWNS,

    // Sacks
    SACKS_ALLOWED,
    SACKS_FORCED,

    // Turnovers
    INTERCEPTIONS_LOST,
    INTERCEPTIONS_FORCED,
    FUMBLES_LOST,
    FUMBLES_FORCED,
    TURNOVERS_LOST,
    TURNOVERS_FORCED,
    TURNOVER_DIFFERENTIAL,
    TURNOVER_TOUCHDOWNS_LOST,
    TURNOVER_TOUCHDOWNS_FORCED,
    PICK_SIXES_THROWN,
    PICK_SIXES_FORCED,
    FUMBLE_RETURN_TDS_COMMITTED,
    FUMBLE_RETURN_TDS_FORCED,

    // Field Goals
    FIELD_GOAL_MADE,
    FIELD_GOAL_ATTEMPTS,
    FIELD_GOAL_PERCENTAGE,
    LONGEST_FIELD_GOAL,
    BLOCKED_OPPONENT_FIELD_GOALS,
    FIELD_GOAL_TOUCHDOWN,

    // Punting
    PUNTS_ATTEMPTED,
    LONGEST_PUNT,
    AVERAGE_PUNT_LENGTH,
    BLOCKED_OPPONENT_PUNT,
    PUNT_RETURN_TD,
    PUNT_RETURN_TD_PERCENTAGE,

    // Kickoffs
    NUMBER_OF_KICKOFFS,
    ONSIDE_ATTEMPTS,
    ONSIDE_SUCCESS,
    ONSIDE_SUCCESS_PERCENTAGE,
    NORMAL_KICKOFF_ATTEMPTS,
    TOUCHBACKS,
    TOUCHBACK_PERCENTAGE,
    KICK_RETURN_TD,
    KICK_RETURN_TD_PERCENTAGE,

    // Game Flow
    NUMBER_OF_DRIVES,
    TIME_OF_POSSESSION,

    // Quarter Scores
    Q1_SCORE,
    Q2_SCORE,
    Q3_SCORE,
    Q4_SCORE,
    OT_SCORE,

    // Touchdowns
    TOUCHDOWNS,

    // Down Conversions
    THIRD_DOWN_CONVERSION_SUCCESS,
    THIRD_DOWN_CONVERSION_ATTEMPTS,
    THIRD_DOWN_CONVERSION_PERCENTAGE,
    FOURTH_DOWN_CONVERSION_SUCCESS,
    FOURTH_DOWN_CONVERSION_ATTEMPTS,
    FOURTH_DOWN_CONVERSION_PERCENTAGE,

    // Game Control
    LARGEST_LEAD,
    LARGEST_DEFICIT,

    // Red Zone
    RED_ZONE_ATTEMPTS,
    RED_ZONE_SUCCESSES,
    RED_ZONE_SUCCESS_PERCENTAGE,
    RED_ZONE_PERCENTAGE,

    // Special Teams
    SAFETIES_FORCED,
    SAFETIES_COMMITTED,

    // Performance Metrics
    AVERAGE_OFFENSIVE_DIFF,
    AVERAGE_DEFENSIVE_DIFF,
    AVERAGE_OFFENSIVE_SPECIAL_TEAMS_DIFF,
    AVERAGE_DEFENSIVE_SPECIAL_TEAMS_DIFF,
    AVERAGE_DIFF,
    AVERAGE_RESPONSE_SPEED,
}
