CREATE TABLE `postseason_season_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `team` varchar(255) NOT NULL,
  `season_number` int(11) NOT NULL,
  `wins` int(11) DEFAULT 0,
  `losses` int(11) DEFAULT 0,
  `subdivision` varchar(50) DEFAULT NULL,
  `pass_attempts` int(11) DEFAULT 0,
  `pass_completions` int(11) DEFAULT 0,
  `pass_completion_percentage` double DEFAULT NULL,
  `pass_yards` int(11) DEFAULT 0,
  `longest_pass` int(11) DEFAULT 0,
  `pass_touchdowns` int(11) DEFAULT 0,
  `pass_successes` int(11) DEFAULT 0,
  `pass_success_percentage` double DEFAULT NULL,
  `rush_attempts` int(11) DEFAULT 0,
  `rush_successes` int(11) DEFAULT 0,
  `rush_success_percentage` double DEFAULT NULL,
  `rush_yards` int(11) DEFAULT 0,
  `longest_run` int(11) DEFAULT 0,
  `rush_touchdowns` int(11) DEFAULT 0,
  `total_yards` int(11) DEFAULT 0,
  `average_yards_per_play` double DEFAULT NULL,
  `first_downs` int(11) DEFAULT 0,
  `sacks_allowed` int(11) DEFAULT 0,
  `sacks_forced` int(11) DEFAULT 0,
  `interceptions_lost` int(11) DEFAULT 0,
  `interceptions_forced` int(11) DEFAULT 0,
  `fumbles_lost` int(11) DEFAULT 0,
  `fumbles_forced` int(11) DEFAULT 0,
  `turnovers_lost` int(11) DEFAULT 0,
  `turnovers_forced` int(11) DEFAULT 0,
  `turnover_differential` int(11) DEFAULT 0,
  `turnover_touchdowns_lost` int(11) DEFAULT 0,
  `turnover_touchdowns_forced` int(11) DEFAULT 0,
  `pick_sixes_thrown` int(11) DEFAULT 0,
  `pick_sixes_forced` int(11) DEFAULT 0,
  `fumble_return_tds_committed` int(11) DEFAULT 0,
  `fumble_return_tds_forced` int(11) DEFAULT 0,
  `field_goal_made` int(11) DEFAULT 0,
  `field_goal_attempts` int(11) DEFAULT 0,
  `field_goal_percentage` double DEFAULT NULL,
  `longest_field_goal` int(11) DEFAULT 0,
  `blocked_opponent_field_goals` int(11) DEFAULT 0,
  `field_goal_touchdown` int(11) DEFAULT 0,
  `punts_attempted` int(11) DEFAULT 0,
  `longest_punt` int(11) DEFAULT 0,
  `average_punt_length` double DEFAULT NULL,
  `blocked_opponent_punt` int(11) DEFAULT 0,
  `punt_return_td` int(11) DEFAULT 0,
  `punt_return_td_percentage` double DEFAULT NULL,
  `number_of_kickoffs` int(11) DEFAULT 0,
  `onside_attempts` int(11) DEFAULT 0,
  `onside_success` int(11) DEFAULT 0,
  `onside_success_percentage` double DEFAULT NULL,
  `normal_kickoff_attempts` int(11) DEFAULT 0,
  `touchbacks` int(11) DEFAULT 0,
  `touchback_percentage` double DEFAULT NULL,
  `kick_return_td` int(11) DEFAULT 0,
  `kick_return_td_percentage` double DEFAULT NULL,
  `number_of_drives` int(11) DEFAULT 0,
  `time_of_possession` int(11) DEFAULT 0,
  `touchdowns` int(11) DEFAULT 0,
  `third_down_conversion_success` int(11) DEFAULT 0,
  `third_down_conversion_attempts` int(11) DEFAULT 0,
  `third_down_conversion_percentage` double DEFAULT NULL,
  `fourth_down_conversion_success` int(11) DEFAULT 0,
  `fourth_down_conversion_attempts` int(11) DEFAULT 0,
  `fourth_down_conversion_percentage` double DEFAULT NULL,
  `largest_lead` int(11) DEFAULT 0,
  `largest_deficit` int(11) DEFAULT 0,
  `red_zone_attempts` int(11) DEFAULT 0,
  `red_zone_successes` int(11) DEFAULT 0,
  `red_zone_success_percentage` double DEFAULT NULL,
  `red_zone_percentage` double DEFAULT NULL,
  `safeties_forced` int(11) DEFAULT 0,
  `safeties_committed` int(11) DEFAULT 0,
  `average_offensive_diff` double DEFAULT NULL,
  `average_defensive_diff` double DEFAULT NULL,
  `average_offensive_special_teams_diff` double DEFAULT NULL,
  `average_defensive_special_teams_diff` double DEFAULT NULL,
  `average_diff` double DEFAULT NULL,
  `average_response_speed` double DEFAULT NULL,
  `last_modified_ts` varchar(255) DEFAULT NULL,
  `conference` varchar(255) DEFAULT NULL,
  `defensive_playbook` varchar(255) DEFAULT NULL,
  `offensive_playbook` varchar(255) DEFAULT NULL,
  `opponent_pass_attempts` int(11) DEFAULT 0 COMMENT 'Total pass attempts allowed',
  `opponent_pass_completions` int(11) DEFAULT 0 COMMENT 'Total pass completions allowed',
  `opponent_pass_completion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average pass completion percentage allowed',
  `opponent_pass_yards` int(11) DEFAULT 0 COMMENT 'Total pass yards allowed',
  `opponent_longest_pass` int(11) DEFAULT 0 COMMENT 'Longest pass allowed',
  `opponent_pass_touchdowns` int(11) DEFAULT 0 COMMENT 'Total pass touchdowns allowed',
  `opponent_pass_successes` int(11) DEFAULT 0 COMMENT 'Total pass successes allowed',
  `opponent_pass_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average pass success percentage allowed',
  `opponent_rush_attempts` int(11) DEFAULT 0 COMMENT 'Total rush attempts allowed',
  `opponent_rush_successes` int(11) DEFAULT 0 COMMENT 'Total rush successes allowed',
  `opponent_rush_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average rush success percentage allowed',
  `opponent_rush_yards` int(11) DEFAULT 0 COMMENT 'Total rush yards allowed',
  `opponent_longest_run` int(11) DEFAULT 0 COMMENT 'Longest run allowed',
  `opponent_rush_touchdowns` int(11) DEFAULT 0 COMMENT 'Total rush touchdowns allowed',
  `opponent_total_yards` int(11) DEFAULT 0 COMMENT 'Total yards allowed',
  `opponent_average_yards_per_play` decimal(5,2) DEFAULT NULL COMMENT 'Average yards per play allowed',
  `opponent_first_downs` int(11) DEFAULT 0 COMMENT 'Total first downs allowed',
  `opponent_field_goal_made` int(11) DEFAULT 0 COMMENT 'Total field goals made against team',
  `opponent_field_goal_attempts` int(11) DEFAULT 0 COMMENT 'Total field goal attempts against team',
  `opponent_field_goal_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average field goal percentage against team',
  `opponent_longest_field_goal` int(11) DEFAULT 0 COMMENT 'Longest field goal against team',
  `opponent_field_goal_touchdown` int(11) DEFAULT 0 COMMENT 'Total field goal touchdowns against team',
  `opponent_punts_attempted` int(11) DEFAULT 0 COMMENT 'Total punts attempted against team',
  `opponent_longest_punt` int(11) DEFAULT 0 COMMENT 'Longest punt against team',
  `opponent_average_punt_length` decimal(5,2) DEFAULT NULL COMMENT 'Average punt length against team',
  `opponent_punt_return_td` int(11) DEFAULT 0 COMMENT 'Total punt return touchdowns against team',
  `opponent_punt_return_td_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average punt return TD percentage against team',
  `opponent_number_of_kickoffs` int(11) DEFAULT 0 COMMENT 'Total kickoffs against team',
  `opponent_onside_attempts` int(11) DEFAULT 0 COMMENT 'Total onside kick attempts against team',
  `opponent_onside_success` int(11) DEFAULT 0 COMMENT 'Total onside kick successes against team',
  `opponent_onside_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average onside kick success percentage against team',
  `opponent_normal_kickoff_attempts` int(11) DEFAULT 0 COMMENT 'Total normal kickoff attempts against team',
  `opponent_touchbacks` int(11) DEFAULT 0 COMMENT 'Total touchbacks against team',
  `opponent_touchback_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average touchback percentage against team',
  `opponent_kick_return_td` int(11) DEFAULT 0 COMMENT 'Total kick return touchdowns against team',
  `opponent_kick_return_td_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average kick return TD percentage against team',
  `opponent_number_of_drives` int(11) DEFAULT 0 COMMENT 'Total drives against team',
  `opponent_time_of_possession` int(11) DEFAULT 0 COMMENT 'Total time of possession against team',
  `opponent_touchdowns` int(11) DEFAULT 0 COMMENT 'Total touchdowns against team',
  `opponent_third_down_conversion_success` int(11) DEFAULT 0 COMMENT 'Total third down conversions against team',
  `opponent_third_down_conversion_attempts` int(11) DEFAULT 0 COMMENT 'Total third down conversion attempts against team',
  `opponent_third_down_conversion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average third down conversion percentage against team',
  `opponent_fourth_down_conversion_success` int(11) DEFAULT 0 COMMENT 'Total fourth down conversions against team',
  `opponent_fourth_down_conversion_attempts` int(11) DEFAULT 0 COMMENT 'Total fourth down conversion attempts against team',
  `opponent_fourth_down_conversion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average fourth down conversion percentage against team',
  `opponent_red_zone_attempts` int(11) DEFAULT 0 COMMENT 'Total red zone attempts against team',
  `opponent_red_zone_successes` int(11) DEFAULT 0 COMMENT 'Total red zone successes against team',
  `opponent_red_zone_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average red zone success percentage against team',
  `opponent_red_zone_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average red zone percentage against team',
  PRIMARY KEY (`id`),
  UNIQUE KEY `postseason_unique_team_season` (`team`,`season_number`),
  KEY `postseason_idx_team` (`team`),
  KEY `postseason_idx_season_number` (`season_number`),
  KEY `postseason_idx_wins_losses` (`wins`,`losses`),
  KEY `postseason_idx_total_yards` (`total_yards`),
  KEY `postseason_idx_touchdowns` (`touchdowns`),
  KEY `postseason_idx_turnover_differential` (`turnover_differential`),
  KEY `postseason_idx_season_stats_opponent_pass_attempts` (`opponent_pass_attempts`),
  KEY `postseason_idx_season_stats_opponent_rush_attempts` (`opponent_rush_attempts`),
  KEY `postseason_idx_season_stats_opponent_total_yards` (`opponent_total_yards`),
  KEY `postseason_idx_season_stats_opponent_touchdowns` (`opponent_touchdowns`),
  KEY `postseason_idx_season_stats_team_season_opponent` (`team`,`season_number`,`opponent_total_yards`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `postseason_conference_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subdivision` varchar(255) NOT NULL,
  `conference` varchar(255) NOT NULL,
  `season_number` int(11) NOT NULL,
  `total_teams` int(11) DEFAULT 0,
  `total_games` int(11) DEFAULT 0,
  `pass_attempts` int(11) DEFAULT 0,
  `pass_completions` int(11) DEFAULT 0,
  `pass_completion_percentage` double DEFAULT NULL,
  `pass_yards` int(11) DEFAULT 0,
  `longest_pass` int(11) DEFAULT 0,
  `pass_touchdowns` int(11) DEFAULT 0,
  `pass_successes` int(11) DEFAULT 0,
  `pass_success_percentage` double DEFAULT NULL,
  `rush_attempts` int(11) DEFAULT 0,
  `rush_successes` int(11) DEFAULT 0,
  `rush_success_percentage` double DEFAULT NULL,
  `rush_yards` int(11) DEFAULT 0,
  `longest_run` int(11) DEFAULT 0,
  `rush_touchdowns` int(11) DEFAULT 0,
  `total_yards` int(11) DEFAULT 0,
  `average_yards_per_play` double DEFAULT NULL,
  `first_downs` int(11) DEFAULT 0,
  `sacks_allowed` int(11) DEFAULT 0,
  `sacks_forced` int(11) DEFAULT 0,
  `interceptions_lost` int(11) DEFAULT 0,
  `interceptions_forced` int(11) DEFAULT 0,
  `fumbles_lost` int(11) DEFAULT 0,
  `fumbles_forced` int(11) DEFAULT 0,
  `turnovers_lost` int(11) DEFAULT 0,
  `turnovers_forced` int(11) DEFAULT 0,
  `turnover_differential` int(11) DEFAULT 0,
  `turnover_touchdowns_lost` int(11) DEFAULT 0,
  `turnover_touchdowns_forced` int(11) DEFAULT 0,
  `pick_sixes_thrown` int(11) DEFAULT 0,
  `pick_sixes_forced` int(11) DEFAULT 0,
  `fumble_return_tds_committed` int(11) DEFAULT 0,
  `fumble_return_tds_forced` int(11) DEFAULT 0,
  `field_goal_made` int(11) DEFAULT 0,
  `field_goal_attempts` int(11) DEFAULT 0,
  `field_goal_percentage` double DEFAULT NULL,
  `longest_field_goal` int(11) DEFAULT 0,
  `blocked_opponent_field_goals` int(11) DEFAULT 0,
  `field_goal_touchdown` int(11) DEFAULT 0,
  `punts_attempted` int(11) DEFAULT 0,
  `longest_punt` int(11) DEFAULT 0,
  `average_punt_length` double DEFAULT NULL,
  `blocked_opponent_punt` int(11) DEFAULT 0,
  `punt_return_td` int(11) DEFAULT 0,
  `punt_return_td_percentage` double DEFAULT NULL,
  `number_of_kickoffs` int(11) DEFAULT 0,
  `onside_attempts` int(11) DEFAULT 0,
  `onside_success` int(11) DEFAULT 0,
  `onside_success_percentage` double DEFAULT NULL,
  `normal_kickoff_attempts` int(11) DEFAULT 0,
  `touchbacks` int(11) DEFAULT 0,
  `touchback_percentage` double DEFAULT NULL,
  `kick_return_td` int(11) DEFAULT 0,
  `kick_return_td_percentage` double DEFAULT NULL,
  `number_of_drives` int(11) DEFAULT 0,
  `time_of_possession` int(11) DEFAULT 0,
  `touchdowns` int(11) DEFAULT 0,
  `third_down_conversion_success` int(11) DEFAULT 0,
  `third_down_conversion_attempts` int(11) DEFAULT 0,
  `third_down_conversion_percentage` double DEFAULT NULL,
  `fourth_down_conversion_success` int(11) DEFAULT 0,
  `fourth_down_conversion_attempts` int(11) DEFAULT 0,
  `fourth_down_conversion_percentage` double DEFAULT NULL,
  `largest_lead` int(11) DEFAULT 0,
  `largest_deficit` int(11) DEFAULT 0,
  `red_zone_attempts` int(11) DEFAULT 0,
  `red_zone_successes` int(11) DEFAULT 0,
  `red_zone_success_percentage` double DEFAULT NULL,
  `red_zone_percentage` double DEFAULT NULL,
  `safeties_forced` int(11) DEFAULT 0,
  `safeties_committed` int(11) DEFAULT 0,
  `average_offensive_diff` double DEFAULT NULL,
  `average_defensive_diff` double DEFAULT NULL,
  `average_offensive_special_teams_diff` double DEFAULT NULL,
  `average_defensive_special_teams_diff` double DEFAULT NULL,
  `average_diff` double DEFAULT NULL,
  `average_response_speed` double DEFAULT NULL,
  `last_modified_ts` varchar(255) DEFAULT NULL,
  `opponent_pass_attempts` int(11) DEFAULT 0 COMMENT 'Total pass attempts allowed by conference teams',
  `opponent_pass_completions` int(11) DEFAULT 0 COMMENT 'Total pass completions allowed by conference teams',
  `opponent_pass_completion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average pass completion percentage allowed by conference teams',
  `opponent_pass_yards` int(11) DEFAULT 0 COMMENT 'Total pass yards allowed by conference teams',
  `opponent_longest_pass` int(11) DEFAULT 0 COMMENT 'Longest pass allowed by conference teams',
  `opponent_pass_touchdowns` int(11) DEFAULT 0 COMMENT 'Total pass touchdowns allowed by conference teams',
  `opponent_pass_successes` int(11) DEFAULT 0 COMMENT 'Total pass successes allowed by conference teams',
  `opponent_pass_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average pass success percentage allowed by conference teams',
  `opponent_rush_attempts` int(11) DEFAULT 0 COMMENT 'Total rush attempts allowed by conference teams',
  `opponent_rush_successes` int(11) DEFAULT 0 COMMENT 'Total rush successes allowed by conference teams',
  `opponent_rush_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average rush success percentage allowed by conference teams',
  `opponent_rush_yards` int(11) DEFAULT 0 COMMENT 'Total rush yards allowed by conference teams',
  `opponent_longest_run` int(11) DEFAULT 0 COMMENT 'Longest run allowed by conference teams',
  `opponent_rush_touchdowns` int(11) DEFAULT 0 COMMENT 'Total rush touchdowns allowed by conference teams',
  `opponent_total_yards` int(11) DEFAULT 0 COMMENT 'Total yards allowed by conference teams',
  `opponent_average_yards_per_play` decimal(5,2) DEFAULT NULL COMMENT 'Average yards per play allowed by conference teams',
  `opponent_first_downs` int(11) DEFAULT 0 COMMENT 'Total first downs allowed by conference teams',
  `opponent_field_goal_made` int(11) DEFAULT 0 COMMENT 'Total field goals made against conference teams',
  `opponent_field_goal_attempts` int(11) DEFAULT 0 COMMENT 'Total field goal attempts against conference teams',
  `opponent_field_goal_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average field goal percentage against conference teams',
  `opponent_longest_field_goal` int(11) DEFAULT 0 COMMENT 'Longest field goal against conference teams',
  `opponent_field_goal_touchdown` int(11) DEFAULT 0 COMMENT 'Total field goal touchdowns against conference teams',
  `opponent_punts_attempted` int(11) DEFAULT 0 COMMENT 'Total punts attempted against conference teams',
  `opponent_longest_punt` int(11) DEFAULT 0 COMMENT 'Longest punt against conference teams',
  `opponent_average_punt_length` decimal(5,2) DEFAULT NULL COMMENT 'Average punt length against conference teams',
  `opponent_punt_return_td` int(11) DEFAULT 0 COMMENT 'Total punt return touchdowns against conference teams',
  `opponent_punt_return_td_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average punt return TD percentage against conference teams',
  `opponent_number_of_kickoffs` int(11) DEFAULT 0 COMMENT 'Total kickoffs against conference teams',
  `opponent_onside_attempts` int(11) DEFAULT 0 COMMENT 'Total onside kick attempts against conference teams',
  `opponent_onside_success` int(11) DEFAULT 0 COMMENT 'Total onside kick successes against conference teams',
  `opponent_onside_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average onside kick success percentage against conference teams',
  `opponent_normal_kickoff_attempts` int(11) DEFAULT 0 COMMENT 'Total normal kickoff attempts against conference teams',
  `opponent_touchbacks` int(11) DEFAULT 0 COMMENT 'Total touchbacks against conference teams',
  `opponent_touchback_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average touchback percentage against conference teams',
  `opponent_kick_return_td` int(11) DEFAULT 0 COMMENT 'Total kick return touchdowns against conference teams',
  `opponent_kick_return_td_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average kick return TD percentage against conference teams',
  `opponent_number_of_drives` int(11) DEFAULT 0 COMMENT 'Total drives against conference teams',
  `opponent_time_of_possession` int(11) DEFAULT 0 COMMENT 'Total time of possession against conference teams',
  `opponent_touchdowns` int(11) DEFAULT 0 COMMENT 'Total touchdowns against conference teams',
  `opponent_third_down_conversion_success` int(11) DEFAULT 0 COMMENT 'Total third down conversions against conference teams',
  `opponent_third_down_conversion_attempts` int(11) DEFAULT 0 COMMENT 'Total third down conversion attempts against conference teams',
  `opponent_third_down_conversion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average third down conversion percentage against conference teams',
  `opponent_fourth_down_conversion_success` int(11) DEFAULT 0 COMMENT 'Total fourth down conversions against conference teams',
  `opponent_fourth_down_conversion_attempts` int(11) DEFAULT 0 COMMENT 'Total fourth down conversion attempts against conference teams',
  `opponent_fourth_down_conversion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average fourth down conversion percentage against conference teams',
  `opponent_red_zone_attempts` int(11) DEFAULT 0 COMMENT 'Total red zone attempts against conference teams',
  `opponent_red_zone_successes` int(11) DEFAULT 0 COMMENT 'Total red zone successes against conference teams',
  `opponent_red_zone_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average red zone success percentage against conference teams',
  `opponent_red_zone_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average red zone percentage against conference teams',
  PRIMARY KEY (`id`),
  UNIQUE KEY `postseason_unique_subdivision_conference_season` (`subdivision`,`conference`,`season_number`),
  KEY `postseason_idx_subdivision` (`subdivision`),
  KEY `postseason_idx_conference` (`conference`),
  KEY `postseason_idx_season_number` (`season_number`),
  KEY `postseason_idx_subdivision_conference_season` (`subdivision`,`conference`,`season_number`),
  KEY `postseason_idx_conference_stats_opponent_pass_attempts` (`opponent_pass_attempts`),
  KEY `postseason_idx_conference_stats_opponent_rush_attempts` (`opponent_rush_attempts`),
  KEY `postseason_idx_conference_stats_opponent_total_yards` (`opponent_total_yards`),
  KEY `postseason_idx_conference_stats_opponent_touchdowns` (`opponent_touchdowns`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `postseason_league_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subdivision` varchar(255) NOT NULL,
  `season_number` int(11) NOT NULL,
  `total_teams` int(11) DEFAULT 0,
  `total_games` int(11) DEFAULT 0,
  `pass_attempts` int(11) DEFAULT 0,
  `pass_completions` int(11) DEFAULT 0,
  `pass_completion_percentage` double DEFAULT 0,
  `pass_yards` int(11) DEFAULT 0,
  `pass_touchdowns` int(11) DEFAULT 0,
  `pass_interceptions` int(11) DEFAULT 0,
  `pass_successes` int(11) DEFAULT 0,
  `pass_success_percentage` double DEFAULT 0,
  `longest_pass` int(11) DEFAULT 0,
  `rush_attempts` int(11) DEFAULT 0,
  `rush_successes` int(11) DEFAULT 0,
  `rush_success_percentage` double DEFAULT 0,
  `rush_yards` int(11) DEFAULT 0,
  `rush_touchdowns` int(11) DEFAULT 0,
  `longest_run` int(11) DEFAULT 0,
  `total_yards` int(11) DEFAULT 0,
  `average_yards_per_play` double DEFAULT 0,
  `first_downs` int(11) DEFAULT 0,
  `sacks_allowed` int(11) DEFAULT 0,
  `sacks_forced` int(11) DEFAULT 0,
  `interceptions_forced` int(11) DEFAULT 0,
  `fumbles_forced` int(11) DEFAULT 0,
  `fumbles_recovered` int(11) DEFAULT 0,
  `defensive_touchdowns` int(11) DEFAULT 0,
  `field_goals_attempted` int(11) DEFAULT 0,
  `field_goals_made` int(11) DEFAULT 0,
  `field_goal_percentage` double DEFAULT 0,
  `longest_field_goal` int(11) DEFAULT 0,
  `punts` int(11) DEFAULT 0,
  `longest_punt` int(11) DEFAULT 0,
  `kickoff_return_touchdowns` int(11) DEFAULT 0,
  `punt_return_touchdowns` int(11) DEFAULT 0,
  `average_offensive_diff` double DEFAULT 0,
  `average_defensive_diff` double DEFAULT 0,
  `average_offensive_special_teams_diff` double DEFAULT 0,
  `average_defensive_special_teams_diff` double DEFAULT 0,
  `average_diff` double DEFAULT 0,
  `average_response_speed` double DEFAULT 0,
  `last_modified_ts` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `postseason_unique_subdivision_season` (`subdivision`,`season_number`),
  KEY `postseason_idx_subdivision` (`subdivision`),
  KEY `postseason_idx_season_number` (`season_number`),
  KEY `postseason_idx_subdivision_season` (`subdivision`,`season_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `postseason_playbook_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `offensive_playbook` varchar(255) NOT NULL,
  `defensive_playbook` varchar(255) NOT NULL,
  `season_number` int(11) NOT NULL,
  `total_teams` int(11) DEFAULT 0,
  `total_games` int(11) DEFAULT 0,
  `pass_attempts` int(11) DEFAULT 0,
  `pass_completions` int(11) DEFAULT 0,
  `pass_completion_percentage` double DEFAULT 0,
  `pass_yards` int(11) DEFAULT 0,
  `pass_touchdowns` int(11) DEFAULT 0,
  `pass_interceptions` int(11) DEFAULT 0,
  `pass_successes` int(11) DEFAULT 0,
  `pass_success_percentage` double DEFAULT 0,
  `longest_pass` int(11) DEFAULT 0,
  `rush_attempts` int(11) DEFAULT 0,
  `rush_successes` int(11) DEFAULT 0,
  `rush_success_percentage` double DEFAULT 0,
  `rush_yards` int(11) DEFAULT 0,
  `rush_touchdowns` int(11) DEFAULT 0,
  `longest_run` int(11) DEFAULT 0,
  `total_yards` int(11) DEFAULT 0,
  `average_yards_per_play` double DEFAULT 0,
  `first_downs` int(11) DEFAULT 0,
  `sacks_allowed` int(11) DEFAULT 0,
  `sacks_forced` int(11) DEFAULT 0,
  `interceptions_forced` int(11) DEFAULT 0,
  `fumbles_forced` int(11) DEFAULT 0,
  `fumbles_recovered` int(11) DEFAULT 0,
  `defensive_touchdowns` int(11) DEFAULT 0,
  `field_goals_attempted` int(11) DEFAULT 0,
  `field_goals_made` int(11) DEFAULT 0,
  `field_goal_percentage` double DEFAULT 0,
  `longest_field_goal` int(11) DEFAULT 0,
  `punts` int(11) DEFAULT 0,
  `longest_punt` int(11) DEFAULT 0,
  `kickoff_return_touchdowns` int(11) DEFAULT 0,
  `punt_return_touchdowns` int(11) DEFAULT 0,
  `average_offensive_diff` double DEFAULT 0,
  `average_defensive_diff` double DEFAULT 0,
  `average_offensive_special_teams_diff` double DEFAULT 0,
  `average_defensive_special_teams_diff` double DEFAULT 0,
  `average_diff` double DEFAULT 0,
  `average_response_speed` double DEFAULT 0,
  `last_modified_ts` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `postseason_unique_offensive_defensive_playbook_season` (`offensive_playbook`,`defensive_playbook`,`season_number`),
  KEY `postseason_idx_offensive_playbook` (`offensive_playbook`),
  KEY `postseason_idx_defensive_playbook` (`defensive_playbook`),
  KEY `postseason_idx_season_number` (`season_number`),
  KEY `postseason_idx_offensive_defensive_playbook_season` (`offensive_playbook`,`defensive_playbook`,`season_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
