ALTER TABLE `schedule`
  ADD COLUMN `neutral_site` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN `venue` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `game`
  ADD COLUMN `neutral_site` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN `venue` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `team`
  ADD COLUMN `stadium` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `conference`
  ADD COLUMN `championship_venue` VARCHAR(255) DEFAULT NULL;

CREATE TABLE `bowl_venue` (
  `name` VARCHAR(255) NOT NULL,
  `venue` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
