-- Baseline snapshot of the production 'arceus' schema as of 2026-07-05.
-- Flyway is baselined at this version in production (see application.properties),
-- so this file only actually runs when building a fresh (empty) database, e.g. for local dev/CI.

/*M!999999\- enable the sandbox mode */ 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*M!100616 SET @OLD_NOTE_VERBOSITY=@@NOTE_VERBOSITY, NOTE_VERBOSITY=0 */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `coach_transaction_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `team` varchar(255) NOT NULL,
  `position` varchar(255) NOT NULL,
  `coach` longtext NOT NULL,
  `transaction` varchar(255) NOT NULL,
  `transaction_date` varchar(255) NOT NULL,
  `processed_by` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `conference_rules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `conference` varchar(255) NOT NULL,
  `num_conference_games` int(11) NOT NULL,
  `protected_rivalries` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`protected_rivalries`)),
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_cgepwxwda8sq0sv7dj6svqdqg` (`conference`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `conference_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subdivision` varchar(255) NOT NULL,
  `conference` varchar(255) NOT NULL,
  `season_number` int(11) NOT NULL,
  `total_teams` int(11) DEFAULT 0,
  `total_games` int(11) DEFAULT 0,
  `pass_attempts` int(11) DEFAULT 0,
  `pass_completions` int(11) DEFAULT 0,
  `pass_completion_percentage` double DEFAULT NULL,
  `pass_yards` int(11) DEFAULT 0,
  `longest_pass` int(11) DEFAULT 0,
  `pass_touchdowns` int(11) DEFAULT 0,
  `pass_successes` int(11) DEFAULT 0,
  `pass_success_percentage` double DEFAULT NULL,
  `rush_attempts` int(11) DEFAULT 0,
  `rush_successes` int(11) DEFAULT 0,
  `rush_success_percentage` double DEFAULT NULL,
  `rush_yards` int(11) DEFAULT 0,
  `longest_run` int(11) DEFAULT 0,
  `rush_touchdowns` int(11) DEFAULT 0,
  `total_yards` int(11) DEFAULT 0,
  `average_yards_per_play` double DEFAULT NULL,
  `first_downs` int(11) DEFAULT 0,
  `sacks_allowed` int(11) DEFAULT 0,
  `sacks_forced` int(11) DEFAULT 0,
  `interceptions_lost` int(11) DEFAULT 0,
  `interceptions_forced` int(11) DEFAULT 0,
  `fumbles_lost` int(11) DEFAULT 0,
  `fumbles_forced` int(11) DEFAULT 0,
  `turnovers_lost` int(11) DEFAULT 0,
  `turnovers_forced` int(11) DEFAULT 0,
  `turnover_differential` int(11) DEFAULT 0,
  `turnover_touchdowns_lost` int(11) DEFAULT 0,
  `turnover_touchdowns_forced` int(11) DEFAULT 0,
  `pick_sixes_thrown` int(11) DEFAULT 0,
  `pick_sixes_forced` int(11) DEFAULT 0,
  `fumble_return_tds_committed` int(11) DEFAULT 0,
  `fumble_return_tds_forced` int(11) DEFAULT 0,
  `field_goal_made` int(11) DEFAULT 0,
  `field_goal_attempts` int(11) DEFAULT 0,
  `field_goal_percentage` double DEFAULT NULL,
  `longest_field_goal` int(11) DEFAULT 0,
  `blocked_opponent_field_goals` int(11) DEFAULT 0,
  `field_goal_touchdown` int(11) DEFAULT 0,
  `punts_attempted` int(11) DEFAULT 0,
  `longest_punt` int(11) DEFAULT 0,
  `average_punt_length` double DEFAULT NULL,
  `blocked_opponent_punt` int(11) DEFAULT 0,
  `punt_return_td` int(11) DEFAULT 0,
  `punt_return_td_percentage` double DEFAULT NULL,
  `number_of_kickoffs` int(11) DEFAULT 0,
  `onside_attempts` int(11) DEFAULT 0,
  `onside_success` int(11) DEFAULT 0,
  `onside_success_percentage` double DEFAULT NULL,
  `normal_kickoff_attempts` int(11) DEFAULT 0,
  `touchbacks` int(11) DEFAULT 0,
  `touchback_percentage` double DEFAULT NULL,
  `kick_return_td` int(11) DEFAULT 0,
  `kick_return_td_percentage` double DEFAULT NULL,
  `number_of_drives` int(11) DEFAULT 0,
  `time_of_possession` int(11) DEFAULT 0,
  `touchdowns` int(11) DEFAULT 0,
  `third_down_conversion_success` int(11) DEFAULT 0,
  `third_down_conversion_attempts` int(11) DEFAULT 0,
  `third_down_conversion_percentage` double DEFAULT NULL,
  `fourth_down_conversion_success` int(11) DEFAULT 0,
  `fourth_down_conversion_attempts` int(11) DEFAULT 0,
  `fourth_down_conversion_percentage` double DEFAULT NULL,
  `largest_lead` int(11) DEFAULT 0,
  `largest_deficit` int(11) DEFAULT 0,
  `red_zone_attempts` int(11) DEFAULT 0,
  `red_zone_successes` int(11) DEFAULT 0,
  `red_zone_success_percentage` double DEFAULT NULL,
  `red_zone_percentage` double DEFAULT NULL,
  `safeties_forced` int(11) DEFAULT 0,
  `safeties_committed` int(11) DEFAULT 0,
  `average_offensive_diff` double DEFAULT NULL,
  `average_defensive_diff` double DEFAULT NULL,
  `average_offensive_special_teams_diff` double DEFAULT NULL,
  `average_defensive_special_teams_diff` double DEFAULT NULL,
  `average_diff` double DEFAULT NULL,
  `average_response_speed` double DEFAULT NULL,
  `last_modified_ts` varchar(255) DEFAULT NULL,
  `opponent_pass_attempts` int(11) DEFAULT 0 COMMENT 'Total pass attempts allowed by conference teams',
  `opponent_pass_completions` int(11) DEFAULT 0 COMMENT 'Total pass completions allowed by conference teams',
  `opponent_pass_completion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average pass completion percentage allowed by conference teams',
  `opponent_pass_yards` int(11) DEFAULT 0 COMMENT 'Total pass yards allowed by conference teams',
  `opponent_longest_pass` int(11) DEFAULT 0 COMMENT 'Longest pass allowed by conference teams',
  `opponent_pass_touchdowns` int(11) DEFAULT 0 COMMENT 'Total pass touchdowns allowed by conference teams',
  `opponent_pass_successes` int(11) DEFAULT 0 COMMENT 'Total pass successes allowed by conference teams',
  `opponent_pass_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average pass success percentage allowed by conference teams',
  `opponent_rush_attempts` int(11) DEFAULT 0 COMMENT 'Total rush attempts allowed by conference teams',
  `opponent_rush_successes` int(11) DEFAULT 0 COMMENT 'Total rush successes allowed by conference teams',
  `opponent_rush_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average rush success percentage allowed by conference teams',
  `opponent_rush_yards` int(11) DEFAULT 0 COMMENT 'Total rush yards allowed by conference teams',
  `opponent_longest_run` int(11) DEFAULT 0 COMMENT 'Longest run allowed by conference teams',
  `opponent_rush_touchdowns` int(11) DEFAULT 0 COMMENT 'Total rush touchdowns allowed by conference teams',
  `opponent_total_yards` int(11) DEFAULT 0 COMMENT 'Total yards allowed by conference teams',
  `opponent_average_yards_per_play` decimal(5,2) DEFAULT NULL COMMENT 'Average yards per play allowed by conference teams',
  `opponent_first_downs` int(11) DEFAULT 0 COMMENT 'Total first downs allowed by conference teams',
  `opponent_field_goal_made` int(11) DEFAULT 0 COMMENT 'Total field goals made against conference teams',
  `opponent_field_goal_attempts` int(11) DEFAULT 0 COMMENT 'Total field goal attempts against conference teams',
  `opponent_field_goal_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average field goal percentage against conference teams',
  `opponent_longest_field_goal` int(11) DEFAULT 0 COMMENT 'Longest field goal against conference teams',
  `opponent_field_goal_touchdown` int(11) DEFAULT 0 COMMENT 'Total field goal touchdowns against conference teams',
  `opponent_punts_attempted` int(11) DEFAULT 0 COMMENT 'Total punts attempted against conference teams',
  `opponent_longest_punt` int(11) DEFAULT 0 COMMENT 'Longest punt against conference teams',
  `opponent_average_punt_length` decimal(5,2) DEFAULT NULL COMMENT 'Average punt length against conference teams',
  `opponent_punt_return_td` int(11) DEFAULT 0 COMMENT 'Total punt return touchdowns against conference teams',
  `opponent_punt_return_td_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average punt return TD percentage against conference teams',
  `opponent_number_of_kickoffs` int(11) DEFAULT 0 COMMENT 'Total kickoffs against conference teams',
  `opponent_onside_attempts` int(11) DEFAULT 0 COMMENT 'Total onside kick attempts against conference teams',
  `opponent_onside_success` int(11) DEFAULT 0 COMMENT 'Total onside kick successes against conference teams',
  `opponent_onside_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average onside kick success percentage against conference teams',
  `opponent_normal_kickoff_attempts` int(11) DEFAULT 0 COMMENT 'Total normal kickoff attempts against conference teams',
  `opponent_touchbacks` int(11) DEFAULT 0 COMMENT 'Total touchbacks against conference teams',
  `opponent_touchback_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average touchback percentage against conference teams',
  `opponent_kick_return_td` int(11) DEFAULT 0 COMMENT 'Total kick return touchdowns against conference teams',
  `opponent_kick_return_td_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average kick return TD percentage against conference teams',
  `opponent_number_of_drives` int(11) DEFAULT 0 COMMENT 'Total drives against conference teams',
  `opponent_time_of_possession` int(11) DEFAULT 0 COMMENT 'Total time of possession against conference teams',
  `opponent_touchdowns` int(11) DEFAULT 0 COMMENT 'Total touchdowns against conference teams',
  `opponent_third_down_conversion_success` int(11) DEFAULT 0 COMMENT 'Total third down conversions against conference teams',
  `opponent_third_down_conversion_attempts` int(11) DEFAULT 0 COMMENT 'Total third down conversion attempts against conference teams',
  `opponent_third_down_conversion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average third down conversion percentage against conference teams',
  `opponent_fourth_down_conversion_success` int(11) DEFAULT 0 COMMENT 'Total fourth down conversions against conference teams',
  `opponent_fourth_down_conversion_attempts` int(11) DEFAULT 0 COMMENT 'Total fourth down conversion attempts against conference teams',
  `opponent_fourth_down_conversion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average fourth down conversion percentage against conference teams',
  `opponent_red_zone_attempts` int(11) DEFAULT 0 COMMENT 'Total red zone attempts against conference teams',
  `opponent_red_zone_successes` int(11) DEFAULT 0 COMMENT 'Total red zone successes against conference teams',
  `opponent_red_zone_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average red zone success percentage against conference teams',
  `opponent_red_zone_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average red zone percentage against conference teams',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_subdivision_conference_season` (`subdivision`,`conference`,`season_number`),
  KEY `idx_subdivision` (`subdivision`),
  KEY `idx_conference` (`conference`),
  KEY `idx_season_number` (`season_number`),
  KEY `idx_subdivision_conference_season` (`subdivision`,`conference`,`season_number`),
  KEY `idx_conference_stats_opponent_pass_attempts` (`opponent_pass_attempts`),
  KEY `idx_conference_stats_opponent_rush_attempts` (`opponent_rush_attempts`),
  KEY `idx_conference_stats_opponent_total_yards` (`opponent_total_yards`),
  KEY `idx_conference_stats_opponent_touchdowns` (`opponent_touchdowns`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `game` (
  `game_id` int(11) NOT NULL AUTO_INCREMENT,
  `home_team` varchar(255) NOT NULL,
  `away_team` varchar(255) NOT NULL,
  `home_coaches` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`home_coaches`)),
  `away_coaches` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`away_coaches`)),
  `home_coach_discord_ids` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`home_coach_discord_ids`)),
  `away_coach_discord_ids` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`away_coach_discord_ids`)),
  `home_offensive_playbook` varchar(255) NOT NULL,
  `away_offensive_playbook` varchar(255) NOT NULL,
  `home_defensive_playbook` varchar(255) NOT NULL,
  `away_defensive_playbook` varchar(255) NOT NULL,
  `home_score` int(11) NOT NULL,
  `away_score` int(11) NOT NULL,
  `waiting_on` varchar(255) NOT NULL,
  `possession` varchar(255) DEFAULT NULL,
  `quarter` int(11) NOT NULL,
  `clock` varchar(255) NOT NULL,
  `ball_location` int(11) NOT NULL,
  `down` int(11) NOT NULL,
  `yards_to_go` int(11) NOT NULL,
  `tv_channel` varchar(255) DEFAULT NULL,
  `home_team_rank` int(11) DEFAULT NULL,
  `home_wins` int(11) DEFAULT NULL,
  `home_losses` int(11) DEFAULT NULL,
  `away_team_rank` int(11) DEFAULT NULL,
  `away_wins` int(11) DEFAULT NULL,
  `away_losses` int(11) DEFAULT NULL,
  `subdivision` varchar(255) DEFAULT NULL,
  `timestamp` datetime DEFAULT NULL,
  `win_probability` double DEFAULT NULL COMMENT 'Current win probability for the game',
  `season` int(11) DEFAULT NULL,
  `week` int(11) DEFAULT NULL,
  `num_plays` int(11) NOT NULL,
  `home_timeouts` int(11) NOT NULL,
  `away_timeouts` int(11) NOT NULL,
  `coin_toss_winner` varchar(255) DEFAULT NULL,
  `coin_toss_choice` varchar(255) DEFAULT NULL,
  `overtime_coin_toss_winner` varchar(255) DEFAULT NULL,
  `overtime_coin_toss_choice` varchar(255) DEFAULT NULL,
  `home_platform` varchar(255) NOT NULL,
  `home_platform_id` varchar(255) DEFAULT NULL,
  `away_platform` varchar(255) DEFAULT NULL,
  `away_platform_id` varchar(255) DEFAULT NULL,
  `last_message_timestamp` datetime DEFAULT NULL,
  `game_timer` varchar(255) DEFAULT NULL,
  `game_warning` varchar(255) DEFAULT NULL,
  `current_play_type` varchar(255) DEFAULT NULL,
  `current_play_id` int(11) DEFAULT NULL,
  `clock_stopped` tinyint(1) DEFAULT NULL,
  `request_message_id` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `game_status` varchar(255) NOT NULL,
  `game_type` varchar(255) DEFAULT NULL,
  `game_mode` varchar(255) DEFAULT NULL,
  `overtime_half` int(11) DEFAULT 0,
  `close_game` tinyint(1) NOT NULL DEFAULT 0,
  `close_game_pinged` tinyint(1) NOT NULL DEFAULT 0,
  `upset_alert` tinyint(1) NOT NULL DEFAULT 0,
  `upset_alert_pinged` tinyint(1) NOT NULL DEFAULT 0,
  `home_vegas_spread` double DEFAULT NULL COMMENT 'Home team Vegas spread (negative = favored, positive = underdog)',
  `away_vegas_spread` double DEFAULT NULL COMMENT 'Away team Vegas spread (negative = favored, positive = underdog)',
  `postseason_game_logo` varchar(500) DEFAULT NULL,
  `postseason_game_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`game_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `game_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `game_id` varchar(255) NOT NULL,
  `team` varchar(255) DEFAULT NULL,
  `coaches` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`coaches`)),
  `tv_channel` varchar(255) DEFAULT NULL,
  `offensive_playbook` varchar(255) DEFAULT NULL,
  `defensive_playbook` varchar(255) DEFAULT NULL,
  `season` int(11) DEFAULT NULL,
  `week` int(11) DEFAULT NULL,
  `subdivision` varchar(255) DEFAULT NULL,
  `score` int(11) DEFAULT NULL,
  `pass_attempts` int(11) DEFAULT NULL,
  `pass_completions` int(11) DEFAULT NULL,
  `pass_completion_percentage` double DEFAULT NULL,
  `pass_yards` int(11) DEFAULT NULL,
  `longest_pass` int(11) DEFAULT NULL,
  `sacks_allowed` int(11) DEFAULT NULL,
  `sacks_forced` int(11) DEFAULT NULL,
  `rush_attempts` int(11) DEFAULT NULL,
  `rush_successes` int(11) DEFAULT NULL,
  `rush_success_percentage` double DEFAULT NULL,
  `pass_successes` int(11) DEFAULT NULL,
  `pass_success_percentage` double DEFAULT NULL,
  `rush_yards` int(11) DEFAULT NULL,
  `longest_run` int(11) DEFAULT NULL,
  `total_yards` int(11) DEFAULT NULL,
  `interceptions_lost` int(11) DEFAULT NULL,
  `interceptions_forced` int(11) DEFAULT NULL,
  `fumbles_lost` int(11) DEFAULT NULL,
  `fumbles_forced` int(11) DEFAULT NULL,
  `turnovers_lost` int(11) DEFAULT NULL,
  `turnovers_forced` int(11) DEFAULT NULL,
  `turnover_touchdowns_lost` int(11) DEFAULT NULL,
  `turnover_touchdowns_forced` int(11) DEFAULT NULL,
  `field_goal_made` int(11) DEFAULT NULL,
  `field_goal_attempts` int(11) DEFAULT NULL,
  `field_goal_percentage` double DEFAULT NULL,
  `longest_field_goal` int(11) DEFAULT NULL,
  `blocked_opponent_field_goals` int(11) DEFAULT NULL,
  `field_goal_touchdown` int(11) DEFAULT NULL,
  `punts_attempted` int(11) DEFAULT NULL,
  `longest_punt` int(11) DEFAULT NULL,
  `average_punt_length` double DEFAULT NULL,
  `blocked_opponent_punt` int(11) DEFAULT NULL,
  `punt_return_td` int(11) DEFAULT NULL,
  `punt_return_td_percentage` double DEFAULT NULL,
  `number_of_kickoffs` int(11) DEFAULT NULL,
  `onside_attempts` int(11) DEFAULT NULL,
  `onside_success` int(11) DEFAULT NULL,
  `onside_success_percentage` double DEFAULT NULL,
  `normal_kickoff_attempts` int(11) DEFAULT NULL,
  `touchbacks` int(11) DEFAULT NULL,
  `touchback_percentage` double DEFAULT NULL,
  `kick_return_td` int(11) DEFAULT NULL,
  `kick_return_td_percentage` double DEFAULT NULL,
  `number_of_drives` int(11) DEFAULT NULL,
  `time_of_possession` int(11) DEFAULT NULL,
  `q1_score` int(11) DEFAULT NULL,
  `q2_score` int(11) DEFAULT NULL,
  `q3_score` int(11) DEFAULT NULL,
  `q4_score` int(11) DEFAULT NULL,
  `ot_score` int(11) DEFAULT NULL,
  `touchdowns` int(11) DEFAULT NULL,
  `average_offensive_diff` double DEFAULT NULL,
  `average_defensive_diff` double DEFAULT NULL,
  `average_offensive_special_teams_diff` double DEFAULT NULL,
  `average_defensive_special_teams_diff` double DEFAULT NULL,
  `average_yards_per_play` double DEFAULT NULL,
  `first_downs` int(11) DEFAULT NULL,
  `third_down_conversion_success` int(11) DEFAULT NULL,
  `third_down_conversion_attempts` int(11) DEFAULT NULL,
  `third_down_conversion_percentage` double DEFAULT NULL,
  `fourth_down_conversion_success` int(11) DEFAULT NULL,
  `fourth_down_conversion_attempts` int(11) DEFAULT NULL,
  `fourth_down_conversion_percentage` double DEFAULT NULL,
  `largest_lead` int(11) DEFAULT NULL,
  `largest_deficit` int(11) DEFAULT NULL,
  `pass_touchdowns` int(11) DEFAULT NULL,
  `rush_touchdowns` int(11) DEFAULT NULL,
  `red_zone_attempts` int(11) DEFAULT NULL,
  `red_zone_successes` int(11) DEFAULT NULL,
  `red_zone_percentage` double DEFAULT NULL,
  `average_diff` double DEFAULT NULL,
  `turnover_differential` int(11) DEFAULT NULL,
  `pick_sixes_forced` int(11) DEFAULT NULL,
  `pick_sixes_thrown` int(11) DEFAULT NULL,
  `fumble_return_tds_forced` int(11) DEFAULT NULL,
  `fumble_return_tds_committed` int(11) DEFAULT NULL,
  `safeties_forced` int(11) DEFAULT NULL,
  `safeties_committed` int(11) DEFAULT NULL,
  `red_zone_success_percentage` double DEFAULT NULL,
  `game_type` varchar(255) DEFAULT NULL,
  `game_status` varchar(255) DEFAULT NULL,
  `average_response_speed` double DEFAULT NULL,
  `last_modified_ts` varchar(255) DEFAULT NULL,
  `team_elo` decimal(10,2) DEFAULT 1500.00,
  PRIMARY KEY (`id`),
  KEY `idx_game_stats_team_elo` (`team_elo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `game_writeup` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `scenario` varchar(255) DEFAULT NULL,
  `play_call` varchar(255) DEFAULT NULL,
  `message` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `league_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subdivision` varchar(255) NOT NULL,
  `season_number` int(11) NOT NULL,
  `total_teams` int(11) DEFAULT 0,
  `total_games` int(11) DEFAULT 0,
  `pass_attempts` int(11) DEFAULT 0,
  `pass_completions` int(11) DEFAULT 0,
  `pass_completion_percentage` double DEFAULT 0,
  `pass_yards` int(11) DEFAULT 0,
  `pass_touchdowns` int(11) DEFAULT 0,
  `pass_interceptions` int(11) DEFAULT 0,
  `pass_successes` int(11) DEFAULT 0,
  `pass_success_percentage` double DEFAULT 0,
  `longest_pass` int(11) DEFAULT 0,
  `rush_attempts` int(11) DEFAULT 0,
  `rush_successes` int(11) DEFAULT 0,
  `rush_success_percentage` double DEFAULT 0,
  `rush_yards` int(11) DEFAULT 0,
  `rush_touchdowns` int(11) DEFAULT 0,
  `longest_run` int(11) DEFAULT 0,
  `total_yards` int(11) DEFAULT 0,
  `average_yards_per_play` double DEFAULT 0,
  `first_downs` int(11) DEFAULT 0,
  `sacks_allowed` int(11) DEFAULT 0,
  `sacks_forced` int(11) DEFAULT 0,
  `interceptions_forced` int(11) DEFAULT 0,
  `fumbles_forced` int(11) DEFAULT 0,
  `fumbles_recovered` int(11) DEFAULT 0,
  `defensive_touchdowns` int(11) DEFAULT 0,
  `field_goals_attempted` int(11) DEFAULT 0,
  `field_goals_made` int(11) DEFAULT 0,
  `field_goal_percentage` double DEFAULT 0,
  `longest_field_goal` int(11) DEFAULT 0,
  `punts` int(11) DEFAULT 0,
  `longest_punt` int(11) DEFAULT 0,
  `kickoff_return_touchdowns` int(11) DEFAULT 0,
  `punt_return_touchdowns` int(11) DEFAULT 0,
  `average_offensive_diff` double DEFAULT 0,
  `average_defensive_diff` double DEFAULT 0,
  `average_offensive_special_teams_diff` double DEFAULT 0,
  `average_defensive_special_teams_diff` double DEFAULT 0,
  `average_diff` double DEFAULT 0,
  `average_response_speed` double DEFAULT 0,
  `last_modified_ts` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_subdivision_season` (`subdivision`,`season_number`),
  KEY `idx_subdivision` (`subdivision`),
  KEY `idx_season_number` (`season_number`),
  KEY `idx_subdivision_season` (`subdivision`,`season_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `new_ranges` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `play_type` varchar(255) DEFAULT NULL,
  `offensive_playbook` varchar(255) DEFAULT NULL,
  `defensive_playbook` varchar(255) DEFAULT NULL,
  `ball_location_lower` int(11) DEFAULT NULL,
  `ball_location_upper` int(11) DEFAULT NULL,
  `distance` int(11) DEFAULT NULL,
  `result` varchar(255) DEFAULT NULL,
  `play_time` int(11) DEFAULT NULL,
  `lower_range` int(11) DEFAULT NULL,
  `upper_range` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `new_signup` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `coach_name` varchar(255) DEFAULT NULL,
  `discord_tag` varchar(255) DEFAULT NULL,
  `discord_id` varchar(255) DEFAULT NULL,
  `team_choice_one` varchar(255) DEFAULT NULL,
  `team_choice_two` varchar(255) DEFAULT NULL,
  `team_choice_three` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `hashed_email` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `offensive_playbook` varchar(255) DEFAULT NULL,
  `defensive_playbook` varchar(255) DEFAULT NULL,
  `salt` varchar(255) DEFAULT NULL,
  `verification_token` varchar(255) DEFAULT NULL,
  `approved` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `play` (
  `play_id` int(11) NOT NULL AUTO_INCREMENT,
  `game_id` int(11) DEFAULT NULL,
  `play_number` int(11) DEFAULT NULL,
  `home_score` int(11) DEFAULT NULL,
  `away_score` int(11) DEFAULT NULL,
  `quarter` int(11) DEFAULT NULL,
  `clock` int(11) DEFAULT NULL,
  `ball_location` int(11) DEFAULT NULL,
  `possession` varchar(255) DEFAULT NULL,
  `down` int(11) DEFAULT NULL,
  `yards_to_go` int(11) DEFAULT NULL,
  `defensive_number` varchar(255) DEFAULT NULL,
  `offensive_number` varchar(255) DEFAULT NULL,
  `defensive_submitter` varchar(255) DEFAULT NULL,
  `defensive_submitter_id` varchar(255) DEFAULT NULL COMMENT 'Discord user ID of the defensive submitter',
  `offensive_submitter` varchar(255) DEFAULT NULL,
  `offensive_submitter_id` varchar(255) DEFAULT NULL COMMENT 'Discord user ID of the offensive submitter',
  `play_call` varchar(255) DEFAULT NULL,
  `result` varchar(255) DEFAULT NULL,
  `difference` int(11) DEFAULT NULL,
  `actual_result` varchar(255) DEFAULT NULL,
  `yards` int(11) DEFAULT NULL,
  `play_time` int(11) DEFAULT NULL,
  `runoff_time` int(11) DEFAULT NULL,
  `win_probability` double DEFAULT NULL COMMENT 'Win probability for the possessing team (0.0 to 1.0)',
  `win_probability_added` double DEFAULT NULL COMMENT 'Change in win probability from previous play',
  `home_team` varchar(255) DEFAULT NULL,
  `away_team` varchar(255) DEFAULT NULL,
  `timeout_used` tinyint(4) DEFAULT NULL,
  `offensive_timeout_called` tinyint(1) DEFAULT NULL,
  `defensive_timeout_called` tinyint(1) DEFAULT NULL,
  `home_timeouts` int(11) DEFAULT NULL,
  `away_timeouts` int(11) DEFAULT NULL,
  `offensive_response_speed` bigint(20) DEFAULT NULL,
  `defensive_response_speed` bigint(20) DEFAULT NULL,
  `play_finished` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`play_id`),
  KEY `idx_play_offensive_submitter_id` (`offensive_submitter_id`),
  KEY `idx_play_defensive_submitter_id` (`defensive_submitter_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `playbook_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `offensive_playbook` varchar(255) NOT NULL,
  `defensive_playbook` varchar(255) NOT NULL,
  `season_number` int(11) NOT NULL,
  `total_teams` int(11) DEFAULT 0,
  `total_games` int(11) DEFAULT 0,
  `pass_attempts` int(11) DEFAULT 0,
  `pass_completions` int(11) DEFAULT 0,
  `pass_completion_percentage` double DEFAULT 0,
  `pass_yards` int(11) DEFAULT 0,
  `pass_touchdowns` int(11) DEFAULT 0,
  `pass_interceptions` int(11) DEFAULT 0,
  `pass_successes` int(11) DEFAULT 0,
  `pass_success_percentage` double DEFAULT 0,
  `longest_pass` int(11) DEFAULT 0,
  `rush_attempts` int(11) DEFAULT 0,
  `rush_successes` int(11) DEFAULT 0,
  `rush_success_percentage` double DEFAULT 0,
  `rush_yards` int(11) DEFAULT 0,
  `rush_touchdowns` int(11) DEFAULT 0,
  `longest_run` int(11) DEFAULT 0,
  `total_yards` int(11) DEFAULT 0,
  `average_yards_per_play` double DEFAULT 0,
  `first_downs` int(11) DEFAULT 0,
  `sacks_allowed` int(11) DEFAULT 0,
  `sacks_forced` int(11) DEFAULT 0,
  `interceptions_forced` int(11) DEFAULT 0,
  `fumbles_forced` int(11) DEFAULT 0,
  `fumbles_recovered` int(11) DEFAULT 0,
  `defensive_touchdowns` int(11) DEFAULT 0,
  `field_goals_attempted` int(11) DEFAULT 0,
  `field_goals_made` int(11) DEFAULT 0,
  `field_goal_percentage` double DEFAULT 0,
  `longest_field_goal` int(11) DEFAULT 0,
  `punts` int(11) DEFAULT 0,
  `longest_punt` int(11) DEFAULT 0,
  `kickoff_return_touchdowns` int(11) DEFAULT 0,
  `punt_return_touchdowns` int(11) DEFAULT 0,
  `average_offensive_diff` double DEFAULT 0,
  `average_defensive_diff` double DEFAULT 0,
  `average_offensive_special_teams_diff` double DEFAULT 0,
  `average_defensive_special_teams_diff` double DEFAULT 0,
  `average_diff` double DEFAULT 0,
  `average_response_speed` double DEFAULT 0,
  `last_modified_ts` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_offensive_defensive_playbook_season` (`offensive_playbook`,`defensive_playbook`,`season_number`),
  KEY `idx_offensive_playbook` (`offensive_playbook`),
  KEY `idx_defensive_playbook` (`defensive_playbook`),
  KEY `idx_season_number` (`season_number`),
  KEY `idx_offensive_defensive_playbook_season` (`offensive_playbook`,`defensive_playbook`,`season_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `ranges` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `play_type` varchar(255) DEFAULT NULL,
  `offensive_playbook` varchar(255) DEFAULT NULL,
  `defensive_playbook` varchar(255) DEFAULT NULL,
  `ball_location_lower` int(11) DEFAULT NULL,
  `ball_location_upper` int(11) DEFAULT NULL,
  `distance` int(11) DEFAULT NULL,
  `result` varchar(255) DEFAULT NULL,
  `play_time` int(11) DEFAULT NULL,
  `lower_range` int(11) DEFAULT NULL,
  `upper_range` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `records` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `record_name` varchar(255) NOT NULL,
  `record_type` varchar(50) NOT NULL,
  `season_number` int(11) NOT NULL,
  `week` int(11) DEFAULT NULL,
  `game_id` int(11) DEFAULT NULL,
  `home_team` varchar(255) DEFAULT NULL,
  `away_team` varchar(255) DEFAULT NULL,
  `record_team` varchar(255) NOT NULL,
  `coach` varchar(255) DEFAULT NULL,
  `record_value` double NOT NULL,
  `previous_record_value` double DEFAULT NULL,
  `previous_record_team` varchar(255) DEFAULT NULL,
  `previous_record_game_id` int(11) DEFAULT NULL,
  `is_tied` tinyint(1) DEFAULT 0,
  `tied_teams` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_record_name_type` (`record_name`,`record_type`),
  KEY `idx_season_number` (`season_number`),
  KEY `idx_record_team` (`record_team`),
  KEY `idx_game_id` (`game_id`),
  KEY `idx_record_value` (`record_value`),
  KEY `idx_season_week` (`season_number`,`week`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `request_message_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_type` varchar(255) NOT NULL,
  `game_id` int(11) NOT NULL,
  `play_id` int(11) DEFAULT NULL,
  `message_id` mediumtext NOT NULL,
  `message_location` varchar(500) DEFAULT NULL,
  `message_ts` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `schedule` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `season` int(11) NOT NULL,
  `week` int(11) NOT NULL,
  `subdivision` varchar(255) NOT NULL,
  `home_team` varchar(255) NOT NULL,
  `away_team` varchar(255) NOT NULL,
  `tv_channel` varchar(255) DEFAULT NULL,
  `game_type` varchar(255) NOT NULL,
  `started` tinyint(1) NOT NULL DEFAULT 0,
  `finished` tinyint(1) DEFAULT 0,
  `home_score` int(11) DEFAULT NULL,
  `away_score` int(11) DEFAULT NULL,
  `playoff_round` int(11) DEFAULT NULL,
  `playoff_home_seed` int(11) DEFAULT NULL,
  `playoff_away_seed` int(11) DEFAULT NULL,
  `game_id` int(11) DEFAULT NULL,
  `postseason_game_name` varchar(255) DEFAULT NULL,
  `postseason_game_logo` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_schedule_game_id` (`game_id`),
  KEY `idx_schedule_season_game_type` (`season`,`game_type`),
  KEY `idx_schedule_season_week` (`season`,`week`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `season` (
  `season_number` int(11) NOT NULL AUTO_INCREMENT,
  `start_date` varchar(255) DEFAULT NULL,
  `end_date` varchar(255) DEFAULT NULL,
  `national_championship_winning_team` varchar(255) DEFAULT NULL,
  `national_championship_losing_team` varchar(255) DEFAULT NULL,
  `national_championship_winning_coach` varchar(255) DEFAULT NULL,
  `national_championship_losing_coach` varchar(255) DEFAULT NULL,
  `current_week` int(11) DEFAULT NULL,
  `current_season` tinyint(1) DEFAULT NULL,
  `schedule_locked` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`season_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `season_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `team` varchar(255) NOT NULL,
  `season_number` int(11) NOT NULL,
  `wins` int(11) DEFAULT 0,
  `losses` int(11) DEFAULT 0,
  `subdivision` varchar(50) DEFAULT NULL,
  `pass_attempts` int(11) DEFAULT 0,
  `pass_completions` int(11) DEFAULT 0,
  `pass_completion_percentage` double DEFAULT NULL,
  `pass_yards` int(11) DEFAULT 0,
  `longest_pass` int(11) DEFAULT 0,
  `pass_touchdowns` int(11) DEFAULT 0,
  `pass_successes` int(11) DEFAULT 0,
  `pass_success_percentage` double DEFAULT NULL,
  `rush_attempts` int(11) DEFAULT 0,
  `rush_successes` int(11) DEFAULT 0,
  `rush_success_percentage` double DEFAULT NULL,
  `rush_yards` int(11) DEFAULT 0,
  `longest_run` int(11) DEFAULT 0,
  `rush_touchdowns` int(11) DEFAULT 0,
  `total_yards` int(11) DEFAULT 0,
  `average_yards_per_play` double DEFAULT NULL,
  `first_downs` int(11) DEFAULT 0,
  `sacks_allowed` int(11) DEFAULT 0,
  `sacks_forced` int(11) DEFAULT 0,
  `interceptions_lost` int(11) DEFAULT 0,
  `interceptions_forced` int(11) DEFAULT 0,
  `fumbles_lost` int(11) DEFAULT 0,
  `fumbles_forced` int(11) DEFAULT 0,
  `turnovers_lost` int(11) DEFAULT 0,
  `turnovers_forced` int(11) DEFAULT 0,
  `turnover_differential` int(11) DEFAULT 0,
  `turnover_touchdowns_lost` int(11) DEFAULT 0,
  `turnover_touchdowns_forced` int(11) DEFAULT 0,
  `pick_sixes_thrown` int(11) DEFAULT 0,
  `pick_sixes_forced` int(11) DEFAULT 0,
  `fumble_return_tds_committed` int(11) DEFAULT 0,
  `fumble_return_tds_forced` int(11) DEFAULT 0,
  `field_goal_made` int(11) DEFAULT 0,
  `field_goal_attempts` int(11) DEFAULT 0,
  `field_goal_percentage` double DEFAULT NULL,
  `longest_field_goal` int(11) DEFAULT 0,
  `blocked_opponent_field_goals` int(11) DEFAULT 0,
  `field_goal_touchdown` int(11) DEFAULT 0,
  `punts_attempted` int(11) DEFAULT 0,
  `longest_punt` int(11) DEFAULT 0,
  `average_punt_length` double DEFAULT NULL,
  `blocked_opponent_punt` int(11) DEFAULT 0,
  `punt_return_td` int(11) DEFAULT 0,
  `punt_return_td_percentage` double DEFAULT NULL,
  `number_of_kickoffs` int(11) DEFAULT 0,
  `onside_attempts` int(11) DEFAULT 0,
  `onside_success` int(11) DEFAULT 0,
  `onside_success_percentage` double DEFAULT NULL,
  `normal_kickoff_attempts` int(11) DEFAULT 0,
  `touchbacks` int(11) DEFAULT 0,
  `touchback_percentage` double DEFAULT NULL,
  `kick_return_td` int(11) DEFAULT 0,
  `kick_return_td_percentage` double DEFAULT NULL,
  `number_of_drives` int(11) DEFAULT 0,
  `time_of_possession` int(11) DEFAULT 0,
  `touchdowns` int(11) DEFAULT 0,
  `third_down_conversion_success` int(11) DEFAULT 0,
  `third_down_conversion_attempts` int(11) DEFAULT 0,
  `third_down_conversion_percentage` double DEFAULT NULL,
  `fourth_down_conversion_success` int(11) DEFAULT 0,
  `fourth_down_conversion_attempts` int(11) DEFAULT 0,
  `fourth_down_conversion_percentage` double DEFAULT NULL,
  `largest_lead` int(11) DEFAULT 0,
  `largest_deficit` int(11) DEFAULT 0,
  `red_zone_attempts` int(11) DEFAULT 0,
  `red_zone_successes` int(11) DEFAULT 0,
  `red_zone_success_percentage` double DEFAULT NULL,
  `red_zone_percentage` double DEFAULT NULL,
  `safeties_forced` int(11) DEFAULT 0,
  `safeties_committed` int(11) DEFAULT 0,
  `average_offensive_diff` double DEFAULT NULL,
  `average_defensive_diff` double DEFAULT NULL,
  `average_offensive_special_teams_diff` double DEFAULT NULL,
  `average_defensive_special_teams_diff` double DEFAULT NULL,
  `average_diff` double DEFAULT NULL,
  `average_response_speed` double DEFAULT NULL,
  `last_modified_ts` varchar(255) DEFAULT NULL,
  `conference` varchar(255) DEFAULT NULL,
  `defensive_playbook` varchar(255) DEFAULT NULL,
  `offensive_playbook` varchar(255) DEFAULT NULL,
  `opponent_pass_attempts` int(11) DEFAULT 0 COMMENT 'Total pass attempts allowed',
  `opponent_pass_completions` int(11) DEFAULT 0 COMMENT 'Total pass completions allowed',
  `opponent_pass_completion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average pass completion percentage allowed',
  `opponent_pass_yards` int(11) DEFAULT 0 COMMENT 'Total pass yards allowed',
  `opponent_longest_pass` int(11) DEFAULT 0 COMMENT 'Longest pass allowed',
  `opponent_pass_touchdowns` int(11) DEFAULT 0 COMMENT 'Total pass touchdowns allowed',
  `opponent_pass_successes` int(11) DEFAULT 0 COMMENT 'Total pass successes allowed',
  `opponent_pass_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average pass success percentage allowed',
  `opponent_rush_attempts` int(11) DEFAULT 0 COMMENT 'Total rush attempts allowed',
  `opponent_rush_successes` int(11) DEFAULT 0 COMMENT 'Total rush successes allowed',
  `opponent_rush_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average rush success percentage allowed',
  `opponent_rush_yards` int(11) DEFAULT 0 COMMENT 'Total rush yards allowed',
  `opponent_longest_run` int(11) DEFAULT 0 COMMENT 'Longest run allowed',
  `opponent_rush_touchdowns` int(11) DEFAULT 0 COMMENT 'Total rush touchdowns allowed',
  `opponent_total_yards` int(11) DEFAULT 0 COMMENT 'Total yards allowed',
  `opponent_average_yards_per_play` decimal(5,2) DEFAULT NULL COMMENT 'Average yards per play allowed',
  `opponent_first_downs` int(11) DEFAULT 0 COMMENT 'Total first downs allowed',
  `opponent_field_goal_made` int(11) DEFAULT 0 COMMENT 'Total field goals made against team',
  `opponent_field_goal_attempts` int(11) DEFAULT 0 COMMENT 'Total field goal attempts against team',
  `opponent_field_goal_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average field goal percentage against team',
  `opponent_longest_field_goal` int(11) DEFAULT 0 COMMENT 'Longest field goal against team',
  `opponent_field_goal_touchdown` int(11) DEFAULT 0 COMMENT 'Total field goal touchdowns against team',
  `opponent_punts_attempted` int(11) DEFAULT 0 COMMENT 'Total punts attempted against team',
  `opponent_longest_punt` int(11) DEFAULT 0 COMMENT 'Longest punt against team',
  `opponent_average_punt_length` decimal(5,2) DEFAULT NULL COMMENT 'Average punt length against team',
  `opponent_punt_return_td` int(11) DEFAULT 0 COMMENT 'Total punt return touchdowns against team',
  `opponent_punt_return_td_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average punt return TD percentage against team',
  `opponent_number_of_kickoffs` int(11) DEFAULT 0 COMMENT 'Total kickoffs against team',
  `opponent_onside_attempts` int(11) DEFAULT 0 COMMENT 'Total onside kick attempts against team',
  `opponent_onside_success` int(11) DEFAULT 0 COMMENT 'Total onside kick successes against team',
  `opponent_onside_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average onside kick success percentage against team',
  `opponent_normal_kickoff_attempts` int(11) DEFAULT 0 COMMENT 'Total normal kickoff attempts against team',
  `opponent_touchbacks` int(11) DEFAULT 0 COMMENT 'Total touchbacks against team',
  `opponent_touchback_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average touchback percentage against team',
  `opponent_kick_return_td` int(11) DEFAULT 0 COMMENT 'Total kick return touchdowns against team',
  `opponent_kick_return_td_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average kick return TD percentage against team',
  `opponent_number_of_drives` int(11) DEFAULT 0 COMMENT 'Total drives against team',
  `opponent_time_of_possession` int(11) DEFAULT 0 COMMENT 'Total time of possession against team',
  `opponent_touchdowns` int(11) DEFAULT 0 COMMENT 'Total touchdowns against team',
  `opponent_third_down_conversion_success` int(11) DEFAULT 0 COMMENT 'Total third down conversions against team',
  `opponent_third_down_conversion_attempts` int(11) DEFAULT 0 COMMENT 'Total third down conversion attempts against team',
  `opponent_third_down_conversion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average third down conversion percentage against team',
  `opponent_fourth_down_conversion_success` int(11) DEFAULT 0 COMMENT 'Total fourth down conversions against team',
  `opponent_fourth_down_conversion_attempts` int(11) DEFAULT 0 COMMENT 'Total fourth down conversion attempts against team',
  `opponent_fourth_down_conversion_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average fourth down conversion percentage against team',
  `opponent_red_zone_attempts` int(11) DEFAULT 0 COMMENT 'Total red zone attempts against team',
  `opponent_red_zone_successes` int(11) DEFAULT 0 COMMENT 'Total red zone successes against team',
  `opponent_red_zone_success_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average red zone success percentage against team',
  `opponent_red_zone_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Average red zone percentage against team',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_team_season` (`team`,`season_number`),
  KEY `idx_team` (`team`),
  KEY `idx_season_number` (`season_number`),
  KEY `idx_wins_losses` (`wins`,`losses`),
  KEY `idx_total_yards` (`total_yards`),
  KEY `idx_touchdowns` (`touchdowns`),
  KEY `idx_turnover_differential` (`turnover_differential`),
  KEY `idx_season_stats_opponent_pass_attempts` (`opponent_pass_attempts`),
  KEY `idx_season_stats_opponent_rush_attempts` (`opponent_rush_attempts`),
  KEY `idx_season_stats_opponent_total_yards` (`opponent_total_yards`),
  KEY `idx_season_stats_opponent_touchdowns` (`opponent_touchdowns`),
  KEY `idx_season_stats_team_season_opponent` (`team`,`season_number`,`opponent_total_yards`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `session` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL,
  `token` varchar(255) NOT NULL,
  `expiration_date` datetime NOT NULL DEFAULT current_timestamp(),
  `created_at` int(11) DEFAULT NULL,
  `expiration_time` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_user_id` (`user_id`),
  CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `team` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `short_name` varchar(255) DEFAULT NULL,
  `abbreviation` varchar(255) DEFAULT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `scorebug_logo` varchar(255) DEFAULT NULL,
  `coach_usernames` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`coach_usernames`)),
  `coach_names` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`coach_names`)),
  `coach_discord_tags` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`coach_discord_tags`)),
  `coach_discord_ids` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`coach_discord_ids`)),
  `primary_color` varchar(255) DEFAULT NULL,
  `secondary_color` varchar(255) DEFAULT NULL,
  `playoff_committee_ranking` int(11) DEFAULT NULL,
  `coaches_poll_ranking` int(11) DEFAULT NULL,
  `subdivision` varchar(255) DEFAULT NULL,
  `offensive_playbook` varchar(255) DEFAULT NULL,
  `defensive_playbook` varchar(255) DEFAULT NULL,
  `conference` varchar(255) DEFAULT NULL,
  `current_wins` int(11) DEFAULT 0,
  `current_losses` int(11) DEFAULT 0,
  `overall_wins` int(11) DEFAULT 0,
  `overall_losses` int(11) DEFAULT 0,
  `current_conference_wins` int(11) DEFAULT 0,
  `current_conference_losses` int(11) DEFAULT 0,
  `overall_conference_wins` int(11) DEFAULT 0,
  `overall_conference_losses` int(11) DEFAULT 0,
  `conference_championship_wins` int(11) DEFAULT 0,
  `conference_championship_losses` int(11) DEFAULT 0,
  `bowl_wins` int(11) DEFAULT 0,
  `bowl_losses` int(11) DEFAULT 0,
  `playoff_wins` int(11) DEFAULT 0,
  `playoff_losses` int(11) DEFAULT 0,
  `national_championship_wins` int(11) DEFAULT 0,
  `national_championship_losses` int(11) DEFAULT 0,
  `is_taken` tinyint(1) DEFAULT 0,
  `active` tinyint(1) DEFAULT 1,
  `current_elo` double DEFAULT 1500 COMMENT 'Current season ELO rating',
  `overall_elo` double DEFAULT 1500 COMMENT 'Overall career ELO rating',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `team_old_conferences` (
  `id` int(11) NOT NULL DEFAULT 0,
  `name` varchar(255) DEFAULT NULL,
  `short_name` varchar(255) DEFAULT NULL,
  `abbreviation` varchar(255) DEFAULT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `scorebug_logo` varchar(255) DEFAULT NULL,
  `coach_usernames` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`coach_usernames`)),
  `coach_names` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`coach_names`)),
  `coach_discord_tags` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`coach_discord_tags`)),
  `coach_discord_ids` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`coach_discord_ids`)),
  `primary_color` varchar(255) DEFAULT NULL,
  `secondary_color` varchar(255) DEFAULT NULL,
  `playoff_committee_ranking` int(11) DEFAULT NULL,
  `coaches_poll_ranking` int(11) DEFAULT NULL,
  `subdivision` varchar(255) DEFAULT NULL,
  `offensive_playbook` varchar(255) DEFAULT NULL,
  `defensive_playbook` varchar(255) DEFAULT NULL,
  `conference` varchar(255) DEFAULT NULL,
  `current_wins` int(11) DEFAULT 0,
  `current_losses` int(11) DEFAULT 0,
  `overall_wins` int(11) DEFAULT 0,
  `overall_losses` int(11) DEFAULT 0,
  `current_conference_wins` int(11) DEFAULT 0,
  `current_conference_losses` int(11) DEFAULT 0,
  `overall_conference_wins` int(11) DEFAULT 0,
  `overall_conference_losses` int(11) DEFAULT 0,
  `conference_championship_wins` int(11) DEFAULT 0,
  `conference_championship_losses` int(11) DEFAULT 0,
  `bowl_wins` int(11) DEFAULT 0,
  `bowl_losses` int(11) DEFAULT 0,
  `playoff_wins` int(11) DEFAULT 0,
  `playoff_losses` int(11) DEFAULT 0,
  `national_championship_wins` int(11) DEFAULT 0,
  `national_championship_losses` int(11) DEFAULT 0,
  `is_taken` tinyint(1) DEFAULT 0,
  `active` tinyint(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `coach_name` varchar(255) NOT NULL,
  `discord_tag` varchar(255) DEFAULT NULL,
  `discord_id` varchar(255) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `hashed_email` varchar(255) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `position` varchar(255) NOT NULL,
  `role` varchar(255) NOT NULL,
  `salt` varchar(255) NOT NULL,
  `team` varchar(255) DEFAULT NULL,
  `delay_of_game_instances` int(11) DEFAULT 0,
  `wins` int(11) NOT NULL DEFAULT 0,
  `losses` int(11) NOT NULL DEFAULT 0,
  `win_percentage` double NOT NULL DEFAULT 0,
  `conference_wins` int(11) DEFAULT 0,
  `conference_losses` int(11) DEFAULT 0,
  `conference_championship_wins` int(11) DEFAULT 0,
  `conference_championship_losses` int(11) DEFAULT 0,
  `bowl_wins` int(11) DEFAULT 0,
  `bowl_losses` int(11) DEFAULT 0,
  `playoff_wins` int(11) DEFAULT 0,
  `playoff_losses` int(11) DEFAULT 0,
  `national_championship_wins` int(11) DEFAULT 0,
  `national_championship_losses` int(11) DEFAULT 0,
  `offensive_playbook` varchar(255) DEFAULT NULL,
  `defensive_playbook` varchar(255) DEFAULT NULL,
  `average_response_time` double DEFAULT NULL,
  `delay_of_game_warning_opt_out` tinyint(1) NOT NULL DEFAULT 0,
  `reset_token` varchar(255) DEFAULT NULL,
  `reset_token_expiration` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_pk` (`username`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `discord_id` (`discord_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*M!100616 SET NOTE_VERBOSITY=@OLD_NOTE_VERBOSITY */;

