CREATE TABLE `team_resume_metric` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `season` int(11) NOT NULL,
  `week` int(11) NOT NULL,
  `team_id` int(11) NOT NULL,
  `overall_wins` int(11) NOT NULL DEFAULT 0,
  `overall_losses` int(11) NOT NULL DEFAULT 0,
  `conference_wins` int(11) NOT NULL DEFAULT 0,
  `conference_losses` int(11) NOT NULL DEFAULT 0,
  `q1_wins` int(11) NOT NULL DEFAULT 0,
  `q1_losses` int(11) NOT NULL DEFAULT 0,
  `th_wins` int(11) NOT NULL DEFAULT 0,
  `th_losses` int(11) NOT NULL DEFAULT 0,
  `q4_wins` int(11) NOT NULL DEFAULT 0,
  `q4_losses` int(11) NOT NULL DEFAULT 0,
  `t25_wins` int(11) NOT NULL DEFAULT 0,
  `t25_losses` int(11) NOT NULL DEFAULT 0,
  `t50_wins` int(11) NOT NULL DEFAULT 0,
  `t50_losses` int(11) NOT NULL DEFAULT 0,
  `t100_wins` int(11) NOT NULL DEFAULT 0,
  `t100_losses` int(11) NOT NULL DEFAULT 0,
  `avg_opponent_composite_rank` double DEFAULT NULL,
  `composite_sos` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_team_resume_metric_slot` (`season`,`week`,`team_id`),
  KEY `idx_team_resume_metric_lookup` (`season`,`week`),
  KEY `idx_team_resume_metric_team` (`team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
