ALTER TABLE team ADD COLUMN tertiary_color VARCHAR(9) NOT NULL DEFAULT '#000000';

ALTER TABLE team_field
    ADD COLUMN end_zone_text_color VARCHAR(9) DEFAULT NULL,
    ADD COLUMN end_zone_outline_color VARCHAR(9) DEFAULT NULL;

ALTER TABLE team_uniform_current
    ADD COLUMN logo_size DOUBLE NOT NULL DEFAULT 1.0,
    ADD COLUMN logo_x DOUBLE NOT NULL DEFAULT 0.0,
    ADD COLUMN logo_y DOUBLE NOT NULL DEFAULT 0.0;

ALTER TABLE team_uniform_history
    ADD COLUMN logo_size DOUBLE NOT NULL DEFAULT 1.0,
    ADD COLUMN logo_x DOUBLE NOT NULL DEFAULT 0.0,
    ADD COLUMN logo_y DOUBLE NOT NULL DEFAULT 0.0;
