ALTER TABLE team_uniform_current
    ADD COLUMN IF NOT EXISTS has_shoulder_stripe TINYINT(1) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS shoulder_stripe_color VARCHAR(9) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS jersey_text VARCHAR(32) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS number_top_text VARCHAR(32) DEFAULT NULL;

ALTER TABLE team_uniform_history
    ADD COLUMN IF NOT EXISTS has_shoulder_stripe TINYINT(1) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS shoulder_stripe_color VARCHAR(9) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS jersey_text VARCHAR(32) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS number_top_text VARCHAR(32) DEFAULT NULL;